/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint
         * @description Reports `ok` once the node has taken a role (leader or follower). Followers report healthy on purpose — see the README's deployment notes.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escapement/admin/engine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Engine status (admin)
         * @description Current role, committed sequence number, the leader's address, and the registered state machines. Served from memory on any node. Lives under /admin because it maps internal cluster topology — only an admin credential may read it.
         */
        get: operations["getEngineStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escapement/pools/{pool}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pool statistics
         * @description Remaining, claimed and total counts. Read from memory; no S3 call.
         */
        get: operations["getPool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escapement/admin/pools/{pool}/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed a pool with codes
         * @description Adds codes to a pool, creating it if absent. Codes already present are ignored, so a retry with an overlapping set is safe. Admin credentials only. The whole set lands in a single log entry — seeding 100k codes writes one multi-megabyte object, which is fine but worth knowing.
         */
        post: operations["seedPool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escapement/pools/{pool}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim the next available code
         * @description Pops one code from the pool and records the claim durably before responding. Retrying with the same `Idempotency-Key` returns the same code rather than consuming another.
         */
        post: operations["claimNext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escapement/pools/{pool}/claims/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up a claim
         * @description Who holds a given code, and when they took it. Served from memory.
         */
        get: operations["getClaim"];
        put?: never;
        /**
         * Claim a specific code
         * @description Redemption of a code the caller already holds. Returns `409` if someone else took it first, `404` if the code is not in this pool.
         */
        post: operations["claimCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escapement/admin/pools/{pool}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Return a claimed code to the pool
         * @description Undoes a claim so the code can be issued again — for a downstream step that failed after the claim succeeded. Admin credentials only, because a careless release re-issues a code someone may already be holding.
         */
        post: operations["releaseCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escapement/quotas/{quota}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quota definition and usage
         * @description Served from memory on whichever node answers, so a follower replies as readily as the leader and its figures may trail the leader by up to one poll interval. A per-subject quota reports one subject's usage: name it with `?subject=`, or omit it and the caller's own identity is used. A credential that carries no identity must pass one, or the request is rejected with `400`.
         */
        get: operations["getQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escapement/admin/quotas/{quota}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Define or redefine a quota
         * @description Sets the ceiling. Redefining preserves recorded usage, so lowering a limit below current usage is allowed and simply leaves it exhausted. Admin credentials only.
         */
        post: operations["defineQuota"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escapement/quotas/{quota}/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consume quota
         * @description Increments usage if the ceiling allows it, atomically. Returns `429` when the increment would exceed the limit — nothing is consumed in that case.
         */
        post: operations["consumeQuota"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthCheck: {
            /** @enum {string} */
            status: "ok" | "starting" | "draining";
            service: string;
            /** @enum {string} */
            role?: "starting" | "leader" | "follower";
            /** Format: date-time */
            timestamp: string;
        };
        EngineStatus: {
            nodeId: string;
            /** @enum {string} */
            role: "starting" | "leader" | "follower";
            /** @description Sequence number of the last committed log entry. */
            seq: number;
            endpoint?: string;
            leaderEndpoint?: string;
            queued?: number;
            draining?: boolean;
            machines: string[];
        };
        SeedRequest: {
            codes: string[];
        };
        SeedResult: {
            pool: string;
            /** @description Codes newly added. Duplicates of existing codes are not counted. */
            added: number;
            remaining: number;
        };
        ClaimRequest: {
            /** @description Who the claim is for. Defaults to the token's subject, which is the right answer for player-facing calls. A service credential claiming on someone's behalf should pass it: its own subject is the service, not the player. */
            by?: string;
            /** @description Opaque data stored with the claim. Bounded on purpose: every claim's metadata lives in engine state and in every snapshot for as long as the claim does, so an unbounded object here is unbounded memory and snapshot growth. Flat string values only. */
            metadata?: {
                [key: string]: string;
            };
        };
        Claim: {
            pool: string;
            code: string;
            by: string;
            /** Format: date-time */
            claimedAt: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        ReleaseRequest: {
            code: string;
            reason?: string;
        };
        ReleaseResult: {
            pool: string;
            code: string;
            remaining: number;
        };
        PoolStats: {
            pool: string;
            remaining: number;
            claimed: number;
            total: number;
        };
        DefineQuotaRequest: {
            /** @description Maximum total that may be consumed. Per subject when `perSubject` is true. */
            limit: number;
            /**
             * @description When true the ceiling applies to each subject independently rather than to the quota as a whole.
             * @default false
             */
            perSubject: boolean;
        };
        ConsumeQuotaRequest: {
            /** @description Required when the quota is per-subject. Defaults to the token subject. */
            subject?: string;
            /** @default 1 */
            amount: number;
        };
        ConsumeResult: {
            quota: string;
            subject?: string;
            used: number;
            limit: number;
            remaining: number;
        };
        /** @description The figures sit under `errors`, which is where every error in this API carries its structured detail. */
        ConsumeRejected: {
            message: string;
            /** @example QUOTA_EXCEEDED */
            code?: string;
            /** @description How much was already used, and the ceiling it would have crossed. */
            errors: {
                used: number;
                limit: number;
            };
        };
        /** @description What a quota is, not how much of it is left. Usage is per subject when `perSubject` is true, so there is no single used/remaining pair that describes the whole quota — read `GET /quotas/{quota}` for that. */
        QuotaDefinition: {
            quota: string;
            limit: number;
            perSubject: boolean;
            /** @description Number of distinct subjects with recorded usage. */
            subjects?: number;
        };
        QuotaState: {
            quota: string;
            limit: number;
            used: number;
            remaining: number;
            perSubject: boolean;
            subject?: string;
            /** @description Number of distinct subjects with recorded usage. */
            subjects?: number;
        };
        Error: {
            message: string;
            code?: string;
            errors?: unknown;
        };
    };
    responses: {
        /** @description Missing, expired, or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Token is valid but not permitted on this operation */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such pool, quota, code, or claim */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The node cannot commit right now — no leader has been elected, the leader is unreachable from this follower, or S3 is failing. */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Pool identifier. Pools are independent allocation sets. */
        PoolName: string;
        QuotaName: string;
        Code: string;
        /** @description Caller-generated key that makes the mutation replayable. A retry with the same key returns the original result instead of performing the mutation twice. Required on every mutating operation — a claim API that burns a code on a network retry is broken in a way users notice. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node is serving */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
            /** @description Node has not finished starting, or is draining */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
    getEngineStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Engine status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getPool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pool identifier. Pools are independent allocation sets. */
                pool: components["parameters"]["PoolName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pool statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    seedPool: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated key that makes the mutation replayable. A retry with the same key returns the original result instead of performing the mutation twice. Required on every mutating operation — a claim API that burns a code on a network retry is broken in a way users notice. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Pool identifier. Pools are independent allocation sets. */
                pool: components["parameters"]["PoolName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeedRequest"];
            };
        };
        responses: {
            /** @description Pool seeded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    claimNext: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated key that makes the mutation replayable. A retry with the same key returns the original result instead of performing the mutation twice. Required on every mutating operation — a claim API that burns a code on a network retry is broken in a way users notice. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Pool identifier. Pools are independent allocation sets. */
                pool: components["parameters"]["PoolName"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ClaimRequest"];
            };
        };
        responses: {
            /** @description Code claimed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The pool has no unclaimed codes left */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pool identifier. Pools are independent allocation sets. */
                pool: components["parameters"]["PoolName"];
                code: components["parameters"]["Code"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The claim */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    claimCode: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated key that makes the mutation replayable. A retry with the same key returns the original result instead of performing the mutation twice. Required on every mutating operation — a claim API that burns a code on a network retry is broken in a way users notice. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Pool identifier. Pools are independent allocation sets. */
                pool: components["parameters"]["PoolName"];
                code: components["parameters"]["Code"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ClaimRequest"];
            };
        };
        responses: {
            /** @description Code claimed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Code is already claimed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    releaseCode: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated key that makes the mutation replayable. A retry with the same key returns the original result instead of performing the mutation twice. Required on every mutating operation — a claim API that burns a code on a network retry is broken in a way users notice. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Pool identifier. Pools are independent allocation sets. */
                pool: components["parameters"]["PoolName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseRequest"];
            };
        };
        responses: {
            /** @description Code returned to the pool */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    getQuota: {
        parameters: {
            query?: {
                /** @description Whose usage to report. Required for a per-subject quota unless the credential names a subject; ignored for a whole-quota ceiling. */
                subject?: string;
            };
            header?: never;
            path: {
                quota: components["parameters"]["QuotaName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quota state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaState"];
                };
            };
            /** @description Per-subject quota asked about without a subject */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    defineQuota: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated key that makes the mutation replayable. A retry with the same key returns the original result instead of performing the mutation twice. Required on every mutating operation — a claim API that burns a code on a network retry is broken in a way users notice. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                quota: components["parameters"]["QuotaName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefineQuotaRequest"];
            };
        };
        responses: {
            /** @description Quota defined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaDefinition"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    consumeQuota: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated key that makes the mutation replayable. A retry with the same key returns the original result instead of performing the mutation twice. Required on every mutating operation — a claim API that burns a code on a network retry is broken in a way users notice. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                quota: components["parameters"]["QuotaName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumeQuotaRequest"];
            };
        };
        responses: {
            /** @description Quota consumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumeResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Consuming this amount would exceed the quota */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumeRejected"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
}
